baseURL: https://mingqi-portfolio.netlify.app/ 
languageCode: en-us
title: Portfolio Website for Mingqi Yin
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
   # subtitle: |-
    #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
    #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Mingqi. This is my portfolio website.
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: London Business School
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: myin.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7826 084393
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Mingqi Yin 2022
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
  #  social:
   #   - icon: fa-twitter
    #    label: Twitter
     #   url: https://www.twitter.com
      #- icon: fa-facebook
       # label: Facebook
    #    url: https://www.facebook.com
     # - icon: fa-instagram
      #  label: Instagram
       # url: https://www.instagram.com
   #   - icon: fa-github
    #    label: GitHub
     #   url: https://www.github.com
      #- icon: fa-linkedin
       # label: LinkedIn
        #url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
#    button1:
  #    - name: Get Started
   #     url: blogs
#    button2:
   #   - name: Log In
     #   url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
  #    - name: Generic Blog
   #     url: blogs/ipsum
    #  - name: Elements
     #   url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: fringe.jpg
        subtitle: My Short Biography
        title: Hello! 
        url: blogs/introduction
      - image: gender_inequality.jpg
        subtitle: Are women paid less in work?
        title: Gender Inequality
        url: blogs/gender_inequality
      - image: youth_risk.jpg
        subtitle: Youth Risk Behavior Surveillance System
        title: Weight vs. Activity Level
        url: blogs/youth_risk


  two:
    buttonText: Get Started
    enable: no
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
    
  
